// <auto-generated />
using System;
using CapoteSolution.Models.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CapoteSolution.Models.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250816131622_ValidationsAndNullValuesInCopier")]
    partial class ValidationsAndNullValuesInCopier
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CapoteSolution.Models.Entities.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("CapoteSolution.Models.Entities.Copier", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("ChargeExtras")
                        .HasColumnType("bit");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ExtraBW")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ExtraColor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("IPAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InvoiceDay")
                        .HasColumnType("int");

                    b.Property<string>("MachineEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MachineModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("MonthlyPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("PlanBW")
                        .HasColumnType("int");

                    b.Property<int?>("PlanColor")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("MachineModelId");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("Copiers");
                });

            modelBuilder.Entity("CapoteSolution.Models.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("CapoteSolution.Models.Entities.MachineModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("TonerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("TonerId");

                    b.ToTable("MachineModels");
                });

            modelBuilder.Entity("CapoteSolution.Models.Entities.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BlackCounter")
                        .HasColumnType("int");

                    b.Property<int?>("BlackDiff")
                        .HasColumnType("int");

                    b.Property<int?>("BlackTonerQty")
                        .HasColumnType("int");

                    b.Property<int>("ColorCounter")
                        .HasColumnType("int");

                    b.Property<int?>("ColorDiff")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CopierId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ExtraBW")
                        .HasColumnType("int");

                    b.Property<int?>("ExtraColor")
                        .HasColumnType("int");

                    b.Property<byte>("ServiceReasonId")
                        .HasColumnType("tinyint");

                    b.Property<Guid?>("TechnicianId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TicketNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CopierId");

                    b.HasIndex("ServiceReasonId");

                    b.HasIndex("TechnicianId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("CapoteSolution.Models.Entities.ServiceReason", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ServiceReasons");

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            Name = "Toner Change"
                        },
                        new
                        {
                            Id = (byte)2,
                            Name = "Monthly Counter"
                        },
                        new
                        {
                            Id = (byte)3,
                            Name = "Maintenance"
                        });
                });

            modelBuilder.Entity("CapoteSolution.Models.Entities.Toner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Yield")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Model")
                        .IsUnique();

                    b.ToTable("Toners");
                });

            modelBuilder.Entity("CapoteSolution.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CapoteSolution.Models.Entities.Copier", b =>
                {
                    b.HasOne("CapoteSolution.Models.Entities.Customer", "Customer")
                        .WithMany("Copiers")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.HasOne("CapoteSolution.Models.Entities.MachineModel", "MachineModel")
                        .WithMany("Copiers")
                        .HasForeignKey("MachineModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("MachineModel");
                });

            modelBuilder.Entity("CapoteSolution.Models.Entities.MachineModel", b =>
                {
                    b.HasOne("CapoteSolution.Models.Entities.Brand", "Brand")
                        .WithMany("MachineModels")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CapoteSolution.Models.Entities.Toner", "Toner")
                        .WithMany("MachineModels")
                        .HasForeignKey("TonerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Toner");
                });

            modelBuilder.Entity("CapoteSolution.Models.Entities.Service", b =>
                {
                    b.HasOne("CapoteSolution.Models.Entities.Copier", "Copier")
                        .WithMany("Services")
                        .HasForeignKey("CopierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CapoteSolution.Models.Entities.ServiceReason", "ServiceReason")
                        .WithMany("Services")
                        .HasForeignKey("ServiceReasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CapoteSolution.Models.Entities.User", "Technician")
                        .WithMany("Services")
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Copier");

                    b.Navigation("ServiceReason");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("CapoteSolution.Models.Entities.Brand", b =>
                {
                    b.Navigation("MachineModels");
                });

            modelBuilder.Entity("CapoteSolution.Models.Entities.Copier", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("CapoteSolution.Models.Entities.Customer", b =>
                {
                    b.Navigation("Copiers");
                });

            modelBuilder.Entity("CapoteSolution.Models.Entities.MachineModel", b =>
                {
                    b.Navigation("Copiers");
                });

            modelBuilder.Entity("CapoteSolution.Models.Entities.ServiceReason", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("CapoteSolution.Models.Entities.Toner", b =>
                {
                    b.Navigation("MachineModels");
                });

            modelBuilder.Entity("CapoteSolution.Models.Entities.User", b =>
                {
                    b.Navigation("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
